name: Publish Agent Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: app/docker/build-push-action@v2
        with:
          context: agent
          file: agent/Dockerfile
          push: true
          tags: |
            kodhive/leek-agent:latest
            kodhive/leek-agent:${{ github.event.release.tag_name }}
          cache-from: type=registry,ref=kodhive/leek-agent:latest
          cache-to: type=registry,ref=kodhive/leek-agent:latest
